# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJb2TtNBTzLKhCYSVwKLvykdvPhpnSwi
"""

# app.py
import streamlit as st
from raedelijn_llm_chatbot import generate_why_this_matters, wcag_rules, personas

st.set_page_config(page_title="Accessibility Explainer", page_icon="🧠")

st.title("🧠 Why This Matters")
st.markdown(
    "This tool explains why specific accessibility issues matter for users with different challenges. "
    "Select a rule and a persona to generate a plain-language explanation designed for non-technical healthcare staff."
)

# Dropdowns for selection
rule_titles = [rule["title"] for rule in wcag_rules]
selected_rule_title = st.selectbox("📜 Select WCAG Rule", rule_titles)
selected_persona = st.selectbox("🧍 Select Persona", personas)

# Generate explanation
if st.button("Why This Matters?"):
    selected_rule = next((rule for rule in wcag_rules if rule["title"] == selected_rule_title), None)

    if selected_rule:
        rule_description = selected_rule["description"]
        explanation = generate_why_this_matters(selected_rule_title, rule_description, selected_persona)

        st.success("Explanation Generated!")
        st.markdown("### 💬 Why this Matters")
        st.write(explanation)
    else:
        st.error("Selected rule not found.")

# Optional: Add expandable context box
with st.expander("ℹ️ Why we built this tool"):
    st.markdown("""
    This interface is part of a value-driven accessibility tool created with Raedelijn.
    It helps non-technical healthcare professionals understand barriers faced by users
    with low literacy, cognitive challenges, or visual impairments.
    """)

# Optional footer
st.markdown("---")
st.caption("Built with ❤️ to promote empathy, inclusion, and transparency in digital health.")